# Generated by Django 3.1 on 2022-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sid', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
