# Generated by Django 3.1 on 2022-03-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='high',
            field=models.FloatField(default=0.0),
        ),
    ]
