# Generated by Django 3.1 on 2022-03-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_stock_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cat',
            field=models.CharField(default='10', max_length=4),
        ),
       
    ]
